# Merge changes in prod branch to the active major release candidate (if exists)
name: merge prod to rc

on:
  push:
    branches:
      - prod
    tags:
      - '[0-9]*.[0-9]*'
      - '[0-9]*.[0-9]*.[0-9]*'

concurrency:
  group: prod-upmerge

permissions:
  contents: 'write'
  id-token: 'write'
  pull-requests: 'write'

jobs:
  prod-upmerge:
    runs-on: ubuntu-latest
    steps:
      - name: Source branch
        run: echo "source_branch=prod" >> $GITHUB_ENV

      - name: Check out the source branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.source_branch }}
          fetch-depth: 0

      - name: Set up git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "noreply@github.com"
          git config --global push.autoSetupRemote true

      - name: Get the latest major rc branch
        run: |
          git fetch origin
          latest_major_rc=$(git branch --format '%(refname:short)' -r --list 'origin/rc_*' --sort=-committerdate | grep -Ex 'origin/rc_[0-9]+' | head -n1)
          echo "latest_major_rc=${latest_major_rc#origin/}" >> $GITHUB_ENV

      - name: Detect if release or tagged commit
        run: |
          # Vérifier si le dernier commit vient d'une branche release/*
          release_branch=$(git log -1 --pretty=%D | grep -o 'release/[0-9.]\+' || true)
          # Vérifier si un tag est attaché
          commit_tag=$(git tag --points-at HEAD || true)

          if [[ -n "$release_branch" || -n "$commit_tag" ]]; then
            echo "to_be_merged=true" >> $GITHUB_ENV
          else
            echo "to_be_merged=false" >> $GITHUB_ENV
          fi

          echo "release_branch=$release_branch"
          echo "commit_tag=$commit_tag"

      - name: Get the target branch
        run: |
          if [[ "${{ env.latest_major_rc }}" == "" ]]; then
            target_branch=main
          else
            target_branch=${{ env.latest_major_rc }}
          fi
          echo "target_branch=${target_branch}" >> $GITHUB_ENV

      - name: Get commit date of the source branch
        run: |
          echo "source_date=$(git log -1 ${{ github.sha }} --format=%cd --date=format:%Y-%m-%d_%H-%M-%S)" >> $GITHUB_ENV

      - name: Get SHA of the source branch
        run: |
          echo "source_sha=${{ github.sha }}" >> $GITHUB_ENV

      - name: Create merge branch
        if: ${{ env.to_be_merged == 'true' }}
        run: |
          merge_branch=resolve_${{ env.source_branch }}_to_${{ env.target_branch }}_at_${{ env.source_date }}_from_${{ env.source_sha }}
          git checkout -b ${merge_branch}
          echo "merge_branch=${merge_branch}" >> $GITHUB_ENV

      - name: Merge the target branch into the merge branch
        if: ${{ env.to_be_merged == 'true' }}
        run: |
          git fetch origin
          git merge origin/${target_branch} --no-commit --no-ff || true
          if git ls-files -u | grep -q .; then
            echo "Merge conflicts detected! Aborting merge."
            git merge --abort
          else
            git commit -m "Merge ${{ env.target_branch }} into ${{ env.merge_branch }}" || true
          fi
          git push origin HEAD
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Create PR
        if: ${{ env.to_be_merged == 'true' }}
        run: |
          pr_url=$(gh pr create --title "Resolve ${{ env.source_branch }} to ${{ env.target_branch }} at ${{ env.source_date }} from ${{ env.source_sha }}" \
          --body "Up-merge" \
          --head "${{ env.merge_branch }}" \
          --base "${{ env.target_branch }}")
          echo "pr_url=${pr_url}" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ github.token }}