name: merge prod to rc

on:
  pull_request:
    types:
      - closed
    branches:
      - 'prod'

concurrency:
  group: release-upmerge

permissions:
  contents: 'write'
  id-token: 'write'
  pull-requests: 'write'

jobs:
  prod-upmerge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Source branch
        run: echo "source_branch=prod" >> $GITHUB_ENV
      - name: PR source branch
        run: echo "pr_source_branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
      - name: Check out the source branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.pr_source_branch }}
          fetch-depth: 0
      - name: Fetch the head branch
        run: |
          git fetch origin ${{ env.pr_source_branch }}:${{ env.pr_source_branch }}
      - name: Set up git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "noreply@github.com"
          git config --global push.autoSetupRemote true

      - name: Get the latest major rc branch
        run: |
          git fetch origin
          latest_major_rc=$(git branch --format '%(refname:short)' -r --list 'origin/rc_*' --sort=-committerdate | grep -Ex 'origin/rc_[0-9]+' | head -n1)
          echo "latest_major_rc=${latest_major_rc#origin/}" >> $GITHUB_ENV
      - name: Get the target branch and check the diff
        run: |
          git fetch origin
          if [[ "${{ env.latest_major_rc }}" == "" ]]; then
            echo "No release candidate branch at all (never or only for the very first time). Exiting"
            exit 0
          elif git merge-base --is-ancestor "origin/${{ env.latest_major_rc }}" "origin/${{ env.source_branch }}"; then
            echo "The latest major release candidate is merged into the current branch (meaning no active major release candidate). Exiting."
            exit 0
          else
            target_branch=${{ env.latest_major_rc }}
          fi
          echo "target_branch=${target_branch}" >> $GITHUB_ENV
          merge_base=$(git merge-base ${{ env.pr_source_branch }} origin/${{env.source_branch}})
          if git log ${merge_base}..${{ env.pr_source_branch }} --oneline --decorate=full | grep -E '([0-9]+\.[0-9]+(\.[0-9]+)?)'; then
            echo "Correct tag found."
            if ! git diff --merge-base --quiet origin/${target_branch}; then
              echo "to_be_merged=true" >> $GITHUB_ENV
            else
              echo "No difference found. Exiting"
              exit 0
            fi
          else
            echo "No tag with the correct format. Exiting"
            exit 0
          fi
      - name: Get commit date of the source branch
        run: echo "source_date=$(git log -1 --format=%cd --date=format:%Y-%m-%d_%H-%M-%S)" >> $GITHUB_ENV
      - name: Get SHA of the source branch
        run: echo "source_sha=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Create merge branch
        if: ${{ env.to_be_merged == 'true' }}
        run: |
          merge_branch=resolve_${{ env.source_branch }}_to_${{ env.target_branch }}_at_${{ env.source_date }}_from_${{ env.source_sha }}
          if git ls-remote --quiet --exit-code --heads origin ${merge_branch}; then
            echo "to_be_merged=false" >> $GITHUB_ENV
            git checkout ${merge_branch}
            if ! gh pr update-branch; then
              echo "The resolve branch cannot be updated"
            fi
          else
            git checkout -b ${merge_branch}
          fi
          echo "merge_branch=${merge_branch}" >> $GITHUB_ENV
      - name: Merge the target branch into the merge branch
        if: ${{ env.to_be_merged == 'true' }}
        run: |
          git merge origin/${target_branch} --no-commit --no-ff || true
          if git ls-files -u | grep -q .; then
            echo "Merge conflicts detected! Aborting merge."
            git merge --abort
          else
            git commit -m "Merge ${{ env.target_branch }} into ${{ env.merge_branch }}" || true
          fi
          git push
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Create PR
        if: ${{ env.to_be_merged == 'true' }}
        run: |
          pr_url=$(gh pr create --title "Resolve ${{ env.source_branch }} to ${{ env.target_branch }} at ${{ env.source_date }} from ${{ env.source_sha }}" \
          --body "Up-merge" \
          --head "${{ env.merge_branch }}" \
          --base "${{ env.target_branch }}")
          echo "pr_url=${pr_url}" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ github.token }}
        continue-on-error: true
      - name: Auto approve
        if: ${{ env.to_be_merged == 'true' }}
        run: |
          gh pr review --approve "${{ env.pr_url }}"
        env:
          GITHUB_TOKEN: ${{secrets.BOT_TOKEN}}
        continue-on-error: true
      - name: Auto merge
        if: ${{ env.to_be_merged == 'true' }}
        run: |
          gh pr merge --auto --merge "${{ env.pr_url }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true